# Generated by Django 4.2.6 on 2025-10-29 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0007_remove_historicalauthorworkflow__created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalauthorworkflow",
            name="id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
