files: ^(backend|backoffice|workflows|ui)/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: [ --pytest-test-first ]
        exclude: '^(?!factories/)'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  # Prettier for the React project
  #- repo: local
  #  hooks:
  #    - id: yarn-lint
  #      name: Lint and format with Prettier
  #      entry: yarn --cwd ui lint
  #      language: node
  #      types_or: [javascript, json, css, scss, markdown]
  #      files: ^ui/.*\.(js|jsx|ts|tsx|json|css|scss|md)$
