# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

#
# This file is an example of what an Invenio production environment would look like.
# Here you can find a HAProxy load balancer which redirects the traffic to the web frontend, based on nginx.
# UI application and REST API are separate.
# There are also a celery worker backend, which can be monitored using Flower, and basics services such as
# a Redis cache, a database, a message broker (RabbitMQ) and ElasticSearch.
#
version: '2.3'
services:
  web-api:
    extends:
      file: docker-services.yml
      service: app
    command: "pipenv run gunicorn invenio_app.wsgi_rest:application -b 0.0.0.0:5001"
    image: inspirehep-web-api
    ports:
      - "5001:5001"
    links:
      - cache
      - es
      - mq
      - db
  # Workerdd
  worker_1:
    extends:
      file: docker-services.yml
      service: app
    restart: "always"
    command: "pipenv run celery worker -B -A inspirehep.celery --loglevel=INFO"
    links:
      - cache
      - es
      - mq
      - db
  # Monitoring
  flower:
    extends:
      file: docker-services.yml
      service: flower
    links:
      - mq
  # Base services
  cache:
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es
volumes:
  static_data:
