# Generated by Django 4.2.6 on 2024-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0011_rename_workflow_id_workflowticket_workflow_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="core",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="is_update",
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("author_create_curation", "Author create curation"),
                    ("author_create_user", "Author create user"),
                    ("author_update_curation", "Author update curation"),
                ],
                default="author_create_curation",
                max_length=30,
            ),
        ),
    ]
