# Generated by Django 4.2.6 on 2025-10-29 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hep", "0003_hepworkflow_journal_coverage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalHepWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("data", models.JSONField()),
                ("_created_at", models.DateTimeField(blank=True, editable=False)),
                ("_updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("HEP_CREATE", "HEP create"),
                            ("HEP_UPDATE", "HEP update"),
                        ],
                        default="HEP_CREATE",
                        max_length=30,
                    ),
                ),
                (
                    "journal_coverage",
                    models.CharField(
                        blank=True,
                        choices=[("full", "Full"), ("partial", "Partial")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("approval", "Waiting for approval"),
                            ("blocked", "Blocked"),
                            ("matching", "Matching"),
                            ("fuzzy_matching", "Fuzzy matching"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="processing",
                        max_length=30,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical hep workflow",
                "verbose_name_plural": "historical hep workflows",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
