# Generated by Django 4.2.6 on 2025-10-29 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0004_historicalhepworkflow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalhepworkflow",
            name="status",
        ),
    ]
