# Generated by Django 4.2.6 on 2025-10-29 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0005_remove_historicalhepworkflow_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalhepworkflow",
            name="_created_at",
        ),
        migrations.RemoveField(
            model_name="historicalhepworkflow",
            name="_updated_at",
        ),
        migrations.RemoveField(
            model_name="historicalhepworkflow",
            name="id",
        ),
        migrations.RemoveField(
            model_name="historicalhepworkflow",
            name="workflow_type",
        ),
    ]
