# Generated by Django 4.2.6 on 2025-10-29 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hep", "0006_remove_historicalhepworkflow__created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhepworkflow",
            name="id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
