# Generated by Django 4.2.6 on 2024-10-01 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workflows", "0012_remove_workflow_core_remove_workflow_is_update_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorWorkflow",
            fields=[
                (
                    "workflow_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="workflows.workflow",
                    ),
                ),
            ],
            bases=("workflows.workflow",),
        ),
    ]
