name: Pull request master

on:
  pull_request_target:
    branches: [master]


jobs:
  test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
