name: Pull request master

on:
  pull_request:
    branches: [master]


jobs:
  test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
