name: Push master

on:
  push:
    branches: [master]


jobs:
  test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  deploy:
    needs: test
    strategy:
      matrix:
        include:
          - application: hep
            image: inspirehep/hep
            id: ${{ needs.test.outputs.backend-image-id }}
          - application: ui
            image: inspirehep/ui
            id: ${{ needs.test.outputs.ui-image-id }}
          - application: editor
            image: inspirehep/editor
            id: ${{ needs.test.outputs.editor-image-id }}
    uses: cern-sis/gh-workflows/.github/workflows/update-image-reference.yml@v3.0.0
    with:
      project: inspire
      application: ${{ matrix.application }}
      namespace: inspire-qa
      image: ${{ matrix.image }}
      ref_type: digest
      new_ref: ${{ matrix.id }}
    secrets:
      PAT: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}

