name: Release

on:
  release:
    types: [released]

defaults:
  run:
    shell: bash

jobs:
  push:
    name: Merge to Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push --force --follow-tags origin ${{ github.ref_name }}:prod

  deploy:
    needs: push
    steps:
      - name: generate payload
        run: >
          printf
          'PAYLOAD={"images":["inspirehep/hep@%s","inspirehep/ui@%s","inspirehep/editor@%s"]}'
            "${{ needs.test.outputs.backend-image-id }}"
            "${{ needs.test.outputs.ui-image-id }}"
            "${{ needs.test.outputs.editor-image-id }}"
          >>$GITHUB_ENV

      - name: send event
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-update@main
        with:
          images: ${{ env.PAYLOAD }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}

