name: Release

on:
  release:
    types: [released]

defaults:
  run:
    shell: bash

jobs:
  push:
    name: Merge to Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push --force --follow-tags origin ${{ github.ref_name }}:prod

  deploy:
    needs: push
    steps:
      - name: send event
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-release@v4.0.0
        with:
          images: |
            "inspirehep/hep@${{ needs.test.outputs.backend-image-id }}"
            "inspirehep/ui@${{ needs.test.outputs.ui-image-id }}"
            "inspirehep/editor@${{ needs.test.outputs.editor-image-id }}"
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}

